MGCERP/MGCERP/Areas/Admin/Controllers/MenuController.cs
using MGCERP.Common.ViewModel;

using MGCERP;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MGCERP.BLL;
using Microsoft.AspNet.Identity;

namespace MGCERP.Areas.Admin.Controllers
{
    public class MenuController : Controller
    {
        // GET: Menu/Mrnu
        public ActionResult Index()
        {
            MenuModel menu = new MenuModel();
            menu.menulist = MenuBLL.GetMenuList();
            //menu.menurolelist = MenuBLL.GetMenuRoleList();
            //menu.Rolelist = MenuModuleBLL.GetRoleList();
            //menu.modulelist = MenuModuleBLL.GetModuleList();
            // menu.menumodulelist = MenuModuleBLL.GetMenuModuleList();
            
            //var menu1 = MenuBLL.GetMenuList();
            return View(menu);
        }
        public ActionResult MenuRoleIndex()
        {
            var menumodule = MenuBLL.GetMenuRoleList();
            return View(menumodule);
        }
        public ActionResult ModuleCompanyIndex()
        {
            var modulelist = MenuModuleBLL.GetMenuModuleList();
            return View(modulelist);
        }
        public ActionResult RoleIndex()
        {
            var Rolelist = MenuModuleBLL.GetRoleList();
            return View(Rolelist);
        }
        public ActionResult ModuleIndex()
        {
            var modulelist = MenuModuleBLL.GetModuleList();
            return View(modulelist);
        }
        public ActionResult CreateMenu(Guid id, Guid UserId)
        {
            MenuRolesModel model = new MenuRolesModel();
            //ViewBag.menulist = MenuBLL.GetMenuList();
            ViewBag.menulist = new SelectList(MenuBLL.GetMenuList(), "Id", "MenuName");
            ViewBag.Rolelist = new SelectList(MenuModuleBLL.GetRoleList(), "Id", "Name");
            var data = MenuBLL.GetRoleByMenuId1(id);
            var id1 = (Guid)data.MenuId;
            var menuname = MenuBLL.GetMenu(id1);
            ViewBag.name = menuname;
            model.AspNetRoleId = id;
            ViewBag.CreatedbyUserId = UserId;
            model.CreatedByUserId = UserId;
            model.MenuId = data.MenuId;
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateMenu(MenuRolesModel model,Guid role,Guid MenuId)
        {
            if (ModelState.IsValid)
            {
                ViewBag.menulist = new SelectList(MenuBLL.GetMenuList(), "Id", "Name");
                ViewBag.Rolelist = new SelectList(MenuModuleBLL.GetRoleList(), "Id", "Name");
                var userid = User.Identity.GetUserId();
                Guid createduserid = new Guid(userid);
                model.CreatedByUserId = createduserid;
                bool create = MenuBLL.CreateRole(model,role,MenuId);
                if (!create)
                {
                    ViewBag.ErroMessage = "Something Went Wrong to save data";
                }
                else
                {
                    ViewBag.SuccessMessage = "Record Saved Successfully.";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        public ActionResult CreateRoleMenu()
        {
            MenuRolesModel model = new MenuRolesModel();
            //ViewBag.menulist = MenuBLL.GetMenuList();
            ViewBag.menulist = new SelectList(MenuBLL.GetMenuList(), "Id", "MenuName");
            ViewBag.Rolelist = new SelectList(MenuModuleBLL.GetRoleList(),"Id","Name");
            
            //var data = MenuBLL.GetRoleByMenuId1(id);
            //model.AspNetRolesId = id;
            //model.CreatedbyUserId = data.CreatedbyUserId;
            //model.MenusId = data.MenusId;
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateRoleMenu(MenuRolesModel model)
        {
            if (ModelState.IsValid)
            {
                ViewBag.menulist = new SelectList(MenuBLL.GetMenuList(), "Id", "MenuName");
                ViewBag.Rolelist = new SelectList(MenuModuleBLL.GetRoleList(), "Id", "Name");
                bool create = MenuBLL.CreateMenuRole(model);
               
                if (!create)
                {
                    ViewBag.ErroMessage = "Something Went Wrong to save data";
                }
                else
                {
                    ViewBag.SuccessMessage = "Record Saved Successfully.";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        
        public ActionResult Create()
        {
            ViewBag.UsersList = new SelectList(MenuBLL.GetCompanyUserList(), "Id", "FullName");
            return View();
        }

        [HttpPost]
        public ActionResult Create(MenuModel model)
        {
            if (ModelState.IsValid)
            {
                model.MenuNumber = 0;
                   var userid = User.Identity.GetUserId();
                Guid Id = new Guid(userid);
                ViewBag.UsersList = new SelectList(MenuBLL.GetCompanyUserList(), "Id", "FullName");

                model.menulist = MenuBLL.GetMenuList();
                bool create = MenuBLL.CreateMenu(model, Id);
                if (!create)
                {
                    ViewBag.ErroMessage = "Something Went Wrong to save data";
                }
                else
                {
                    ViewBag.SuccessMessage = "Record Saved Successfully.";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        public ActionResult CreateModule(string id)
        {
            ModuleModel model = new ModuleModel();
            ViewBag.UsersList = new SelectList(MenuBLL.GetCompanyUserList(), "Id", "FullName");
           
            //model.CreatedByUserId = id;
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateModule(ModuleModel model)
        {
            if (ModelState.IsValid)
            {
                var userid = User.Identity.GetUserId();
                Guid Id = new Guid(userid);
                bool create = MenuBLL.CreateModule(model, Id);
                if (!create)
                {
                    ViewBag.ErroMessage = "Something Went Wrong to save data";
                }
                else
                {
                    ViewBag.SuccessMessage = "Record Saved Successfully.";
                    return RedirectToAction("Index");
                }
            }
            else
            {

            }
            return View(model);
        }
        public ActionResult CreateMenuModule()
        {
            MenuModuleModel model = new MenuModuleModel();
            ViewBag.menulist = new SelectList(MenuBLL.GetMenuList(), "Id", "MenuName");
            ViewBag.modulelist = new SelectList(MenuModuleBLL.GetModuleList(), "Id", "ModuleName");
            //ViewBag.UsersList = new SelectList(MenuBLL.GetCompanyUserList(), "Id", "FullName");                                
            return View(model);
        }

        [HttpPost]
        //public ActionResult CreateMenuModule(MenuModuleModel model,Guid ModuleId,Guid CreatedByUserId)
               public ActionResult CreateMenuModule(MenuModuleModel model)
        {
            if (ModelState.IsValid)
            {
                ViewBag.menulist = new SelectList(MenuBLL.GetMenuList(), "Id", "MenuName");
                model.CompanyModuleId = model.CompanyModuleId;                
                var userid = User.Identity.GetUserId();
                Guid Id = new Guid(userid);
                bool create = MenuModuleBLL.Createmodule(model,Id);
                if (!create)
                {
                    ViewBag.ErroMessage = "Something Went Wrong to save data";
                }
                else
                {
                    ViewBag.SuccessMessage = "Record Saved Successfully.";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        public ActionResult EditRole(Guid id,Guid UserId)
        {
            MenuRolesModel menu = new MenuRolesModel();
            ViewBag.RoleList = new SelectList(MenuBLL.GetRoleList(), "Id", "Name");
                var role = MenuBLL.GetRoleByMenu(id);
                var rolename = MenuBLL.GetAspRoleName(role);
                menu.AspNetRoleId =role;
                menu.RoleName = rolename;
                menu.CreatedByUserId = UserId;
                menu.MenuId = id;
                return View(menu);
            
        }
        [HttpPost]
        public ActionResult EditRole(MenuRolesModel model,Guid role)
        {
            if (ModelState.IsValid)
            {
                bool menu = MenuBLL.EditRole(model, role);
                if (!menu)
                {
                    ViewBag.ErroMessage = "Something Went Wrong";
                }
                else
                {
                    ViewBag.SuccessMessage = " Record Saved Successfully.";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        public ActionResult EditAspRole(string id)
        {
            var menu = MenuBLL.GetAspRoleId(id);

            return View(menu);

        }
        [HttpPost]
        public ActionResult EditAspRole(AspRoleModel model)
        {
            if (ModelState.IsValid)
            {
                bool menu = MenuBLL.EditAspRole(model);
                if (!menu)
                {
                    ViewBag.ErroMessage = "Something Went Wrong";
                }
                else
                {
                    ViewBag.SuccessMessage = " Record Saved Successfully.";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        

MGCERP/MGCERP/Areas/Admin/Views/Menu/CreateMenuModule.cshtml
@model MGCERP.Common.ViewModel.MenuModuleModel

@{
    ViewBag.Title = "CreateMenuModule";
    Layout = null;
}


                            @using (Html.BeginForm("CreateMenuModule","Menu",FormMethod.Post, new { @Id = "CreateMenuModule" }))
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-horizontal">
                                
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })   
                                    <div class="col-md-4 col-sm-4 col-xs-12">
                                        <label for="exampleInputlength">Menu Name</label>
                                    </div>
                                    <div class="col-md-8 col-sm-8 col-xs-12">
                                        @Html.DropDownList("MenuId", ViewBag.menulist as SelectList, new { id = "menuid", Text = "MenuId", value = "MenuId", @class = "form-control" })
                                    </div>
                                    <br />
                                    <br />
                                    <br />
                               
                                    <div class="col-md-4 col-sm-4 col-xs-12">
                                        <label for="exampleInputlength">Module Name</label>
                                    </div>
                                    <div class="col-md-8 col-sm-8 col-xs-12">
                                        @Html.DropDownList("CompanyModuleId", ViewBag.modulelist as SelectList, new { id = "CompanyModuleId", Text = "CompanyModuleId", value = "CompanyModuleId", @class = "form-control" })
                                    </div>
                                    <br />
                                    <br />
                                    <br />
                                  
                                    @*<div class="col-md-4 col-sm-4 col-xs-12">
                                        <label for="exampleInputlength">UserName</label>
                                    </div>
                                    <div class="col-md-8 col-sm-8 col-xs-12">
                                        @Html.DropDownList("CreatedByUserId", ViewBag.UsersList as SelectList, "-select-", new { id = "userid", Text = "CreatedByUserId", value = "CreatedByUserId", @class = "form-control" })
                                    </div>
                                    <br />
                                    <br />
                                    <br />*@
                                    
                                    <div class="col-md-4 col-sm-4 col-xs-12">
                                        <label for="exampleInputlength">IsActive</label>
                                    </div>
                                    <div class="col-md-8 col-sm-8 col-xs-12">
                                     @Html.CheckBoxFor(model => model.IsActive, new { @Id = "IsActive" })
                                    </div>
                                    <br />
                                    <br />
                                    <div class="modal-footer">
                                        <div class="" role="group" aria-label="group button">
                                            <div class=" btn-delete hidden" role="group">
                                                <button type="button" id="delImage" class="btn btn-default btn-hover-red" data-dismiss="modal" role="button">Delete</button>
                                            </div>
                                            <div class="" role="group">
                                                <button type="submit" id="saveImage" style="float: left;margin-left: 261px;" class="btn btn-info submit-in-modal-btn" data-action="save" role="button">submit</button>
                                            </div>
                                            <div class="" role="group">
                                                <button type="button" class="btn btn-default close-in-modal-btn" data-dismiss="modal" role="button">Close</button>
                                            </div>
                                        </div>
                                    </div>
                                    @*<div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="Create" class="btn btn-default" />
                                        </div>
                                    </div>*@
                                </div>
                            }

                            <div>
                                @Html.ActionLink("Back to List", "Index")
                            </div>
                       
  @*<script>

      $('form#CreateMenuModule').submit(function(event) {          
          var a = $("#menuid").val();
          var b = $("#CompanyModuleId").val();          
          if (b == null || b == "") {
              alert("Please Select Menu Name")
              return false;

          }
          else if (b == null || b == "") {
              alert("Please Select Module Name")
              return false;
          }                
      });     
  </script>*@

MGCERP/MGCERP/Areas/Admin/Views/Menu/CreateRoleMenu.cshtml
@model MGCERP.Common.ViewModel.MenuRolesModel

@{
    ViewBag.Title = "CreateMenu";
    Layout = null;
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    @using (Html.BeginForm("CreateRoleMenu", "Menu", FormMethod.Post, new { id = "CreateRoleMenu", name= "form_name", Area ="Admin" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="col-md-4 col-sm-4 col-xs-12">
                <label for="exampleInputlength">Menu Name</label>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-12">
                @Html.DropDownList("MenuId", ViewBag.menulist as SelectList, new { id = "MennuId", Text = "MenuId", value = "MenuId", @class = "form-control" })
            </div>
            <br />
            <br />
            <br />

            <div class="col-md-4 col-sm-4 col-xs-12">
                <label for="exampleInputlength">Role Name</label>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-12">
                @Html.DropDownList("AspNetRoleId", ViewBag.Rolelist as SelectList,new { id = "AspNetRoleId", Text = "role", value = "role", @class = "form-control" })
                @*@Html.DropDownList("ModuleId", ViewBag.modulelist as SelectList, "-select-", new { id = "moduleid", Text = "ModuleId", value = "ModuleId", @class = "form-control" })*@
            </div>
            <br />
            <br />
            <br />

            @*<div class="col-md-4 col-sm-4 col-xs-12">
                    <label for="exampleInputlength">UserName</label>
                </div>
                <div class="col-md-8 col-sm-8 col-xs-12">
                    @Html.DropDownList("CreatedByUserId", ViewBag.UsersList as SelectList, "-select-", new { id = "userid", Text = "CreatedByUserId", value = "CreatedByUserId", @class = "form-control" })
                </div>
                <br />
                <br />
                <br />*@

            <div class="col-md-4 col-sm-4 col-xs-12">
                <label for="exampleInputlength">IsActive</label>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-12">
                @Html.CheckBoxFor(model => model.IsActive, new { @Id = "IsActive" })
            </div>
            <br />
            <br />
            <div class="modal-footer">
                <div class="" role="group" aria-label="group button">
                    <div class=" btn-delete hidden" role="group">
                        <button type="button" id="delImage" class="btn btn-default btn-hover-red" data-dismiss="modal" role="button">Delete</button>
                    </div>
                    <div class="" role="group">
                        <button type="submit" id="saveImage" style="float: left;margin-left: 261px;" class="btn btn-info submit-in-modal-btn" data-action="save" role="button">submit</button>
                    </div>
                    <div class="" role="group">
                        <button type="button" class="btn btn-default close-in-modal-btn" data-dismiss="modal" role="button">Close</button>
                    </div>
                </div>
            </div>
            @*<div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>*@
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    <script>
        //$('form#CreateRoleMenu').submit(function (event) {          
        //    var a = $("#MennuId").val();
        //    var b = $("#AspNetRoleId").val();
           
        // if (a == null || a == "")
        // {
        //   alert("Please Select Menu Name")
        //        return false;
        //    }
        //    else if (b == null || b == "") {
        //        alert("Please Select Role Name")
        //        return false;
        //    }
        //});        
    </script>   

MGCERP/MGCERP/Areas/Admin/Views/Menu/EditMenu.cshtml
@model MGCERP.Common.ViewModel.MenuModel
@{ 
    Layout = null;
}
@Html.HiddenFor(model => model.Id)
<div class="container">
    <div class="col-md-12 col-xs-12 col-sm-12">
        <div class="col-md-6 col-xs-12 col-sm-6">
            @using (Html.BeginForm("EditMenu", "Menu", FormMethod.Post, new { id = "MenuEdit", Area = "Admin" }))
            {
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <label for="exampleInputname">Menu Number</label>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            @Html.TextBoxFor(model => model.MenuNumber, new { @class = "form-control" })  <br />
                        </div>
                      
                        <div class="clearfix"></div>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <label for="exampleInputlength">Menu Name</label>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            @Html.TextBoxFor(model => model.MenuName, new { @class = "form-control", @Id = "MenuName", placeholder = "Menu Name" })
                            <br />     @Html.ValidationMessageFor(model => model.MenuName)
                        </div>
                      <div class="clearfix"></div>
                       
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <label for="exampleInputdates">Parent Number</label>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            @Html.TextBoxFor(model => model.ParentNumber, new { @class = "form-control" })  <br />
                        </div>
                        <div class="clearfix"></div>

                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <label for="exampleInputdates">Sort Order</label>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            @Html.TextBoxFor(model => model.SortOrder, new { @class = "form-control" })  <br />
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <label for="exampleInputdates">Active</label>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                        <p>
                            @Html.CheckBoxFor(model => model.IsActive, new { @Id = "IsActive" })
                        </p>
                            </div><div class="clearfix"></div>
                        <div class="col-md-4">
                            @Html.ActionLink("Cancel", "Index", new { @class = "btn btn-primary" })
                            </div>
                      
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <input type="submit" value="Update" class="btn btn-default" />
                        </div>
                        @*</div>*@
                    </div>
                </div>

            }
        </div>
        <div class="col-md-3 col-xs-12 col-sm-3">
            
                @*<div class="col-md-3 col-sm-3 col-xs-12">
                    @Html.ActionLink("Add new Role", "AddRole", new { menuID = Model.Id }, new { @class = "btn btn-info" })
                   <br /><br />
                </div>*@   
            <div class="clearfix"></div>
            
                @{Html.RenderAction("aspnetRoleCreate", "Menu");} <br />           
            <div class="table">
                <table id="featured-datatable" class="table table-sorting table-striped table-hover datatable">
                    <thead>
                        <tr>
                            <th>
                                Action
                            </th>
                            <th>
                                Name
                            </th>

                        </tr>
                    </thead>
                    @if (Model.Rolelist !=null)
                    {
                        <tbody id="menutable">
                            @foreach (var item in Model.Rolelist)
                            {
                                <tr>
                                    <td>
                                        @*@Html.ActionLink("Delete", "aspnetRoleDelete", new { id = item.Id })*@
                                        @Html.ActionLink("Delete", "aspnetRoleDelete", new { menuId = Model.Id, Roleid = item.Id})
                                    </td>
                                    <td>
                                        @item.Name
                                    </td>
                                </tr>
                            }
                        </tbody>
                        }
                </table>
            </div>

            </div>
        <div class="col-md-3 col-xs-12 col-sm-3">
           
                @*<div class="col-md-3 col-sm-3 col-xs-12">
                    @Html.ActionLink("Add New Module", "AddModule", new { menuID = Model.Id }, new { @class = "btn btn-info" })
                  </div>*@ <div class="clearfix"></div>

    @{Html.RenderAction("companyModuleCreate", "Menu");}<br />
<div class="table">
                        <table id="featured-datatable" class="table table-sorting table-striped table-hover datatable">
                            <thead>
                                <tr>
                                    <th>
                                        Action
                                    </th>
                                    <th>
                                        Company Module
                                    </th>

                                </tr>
                            </thead>
@if (Model.companymenumodulelist.Count > 0)
{
                            <tbody id="menutable">
                                @foreach (var item in Model.companymenumodulelist)
                                {
                                    <tr>
                                        <td>                                            
                                            @*@Html.ActionLink("Delete", "MenusCompanyModulesDelete", new { id = item.Id })*@
                                            @Html.ActionLink("Delete", "MenusCompanyModulesDelete", new { menuId = Model.Id, ModuleId = item.Id })
                                        </td>
                                        <td>
                                            @item.ModuleName
                                        </td>
                                    </tr>
                                }
                            </tbody>
}
                        </table>

                </div>

        </div>
        </div>
    </div>


    <div class="clearfix"></div>
    <br>

MGCERP/MGCERP/Areas/Admin/Views/Menu/EditModule.cshtml
@model MGCERP.Common.ViewModel.ModuleModel

@{
    ViewBag.Title = "EditRole";
    Layout = null;
}

   
                            @using (Html.BeginForm("EditModule","Menu",FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-horizontal">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.Id)

                                    <div class="col-md-4 col-sm-4 col-xs-12">
                                        <label for="exampleInputlength">Module Name</label>
                                    </div>
                                    <div class="col-md-8 col-sm-8 col-xs-12">
                                        @Html.EditorFor(model => model.ModuleName, new { @class = "form-control", id = "Name", Text = "Name", value = "Name" })

                                    </div>
                                    <br />
                                    <br />
                                    <br />
                                    @*<div class="form-group">
                                            @Html.LabelFor(model => model.ModuleName, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.ModuleName, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.ModuleName, "", new { @class = "text-danger" })
                                            </div>
                                        </div>*@
                                    <div class="col-md-4 col-sm-4 col-xs-12">
                                        <label for="exampleInputlength">IsActive</label>
                                    </div>
                                    <div class="col-md-8 col-sm-8 col-xs-12">
                                        @Html.CheckBoxFor(model => model.IsActive, new { @Id = "IsActive" })
                                    </div>
                                    <br />
                                    <br />

                                    <div class="modal-footer">
                                        <div class="" role="group" aria-label="group button">
                                            <div class=" btn-delete hidden" role="group">
                                                <button type="button" id="delImage" class="btn btn-default btn-hover-red" data-dismiss="modal" role="button">Delete</button>
                                            </div>
                                            <div class="" role="group">
                                                <button type="submit" id="saveImage" style="float: left;margin-left: 362px;" class="btn btn-info submit-in-modal-btn" data-action="save" role="button">submit</button>
                                            </div>
                                            <div class="" role="group">
                                                <button type="button" class="btn btn-default close-in-modal-btn" data-dismiss="modal" role="button">Close</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                   
                            }

                            <div>
                                @Html.ActionLink("Back to List", "Index")
                            </div>