MGCERP/MGCERP/Areas/Admin/Controllers/MenuController.cs
using MGCERP.Common.ViewModel;

using MGCERP;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MGCERP.BLL;
using Microsoft.AspNet.Identity;

namespace MGCERP.Areas.Admin.Controllers
{
    public class MenuController : Controller
    {
        // GET: Menu/Mrnu
        public ActionResult Index()
        {
            MenuModel menu = new MenuModel();
            menu.menulist = MenuBLL.GetMenuList();
            //menu.menurolelist = MenuBLL.GetMenuRoleList();
            //menu.Rolelist = MenuModuleBLL.GetRoleList();
            //menu.modulelist = MenuModuleBLL.GetModuleList();
            // menu.menumodulelist = MenuModuleBLL.GetMenuModuleList();
            
            //var menu1 = MenuBLL.GetMenuList();
            return View(menu);
        }
        public ActionResult MenuRoleIndex()
        {
            var menumodule = MenuBLL.GetMenuRoleList();
            return View(menumodule);
        }
        public ActionResult ModuleCompanyIndex()
        {
            var modulelist = MenuModuleBLL.GetMenuModuleList();
            return View(modulelist);
        }
        public ActionResult RoleIndex()
        {
            var Rolelist = MenuModuleBLL.GetRoleList();
            return View(Rolelist);
        }
        public ActionResult ModuleIndex()
        {
            var modulelist = MenuModuleBLL.GetModuleList();
            return View(modulelist);
        }
        public ActionResult CreateMenu(Guid id, Guid UserId)
        {
            MenuRolesModel model = new MenuRolesModel();
            //ViewBag.menulist = MenuBLL.GetMenuList();
            ViewBag.menulist = new SelectList(MenuBLL.GetMenuList(), "Id", "MenuName");
            ViewBag.Rolelist = new SelectList(MenuModuleBLL.GetRoleList(), "Id", "Name");
            var data = MenuBLL.GetRoleByMenuId1(id);
            var id1 = (Guid)data.MenuId;
            var menuname = MenuBLL.GetMenu(id1);
            ViewBag.name = menuname;
            model.AspNetRoleId = id;
            ViewBag.CreatedbyUserId = UserId;
            model.CreatedByUserId = UserId;
            model.MenuId = data.MenuId;
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateMenu(MenuRolesModel model,Guid role,Guid MenuId)
        {
            if (ModelState.IsValid)
            {
                ViewBag.menulist = new SelectList(MenuBLL.GetMenuList(), "Id", "Name");
                ViewBag.Rolelist = new SelectList(MenuModuleBLL.GetRoleList(), "Id", "Name");
                var userid = User.Identity.GetUserId();
                Guid createduserid = new Guid(userid);
                model.CreatedByUserId = createduserid;
                bool create = MenuBLL.CreateRole(model,role,MenuId);
                if (!create)
                {
                    ViewBag.ErroMessage = "Something Went Wrong to save data";
                }
                else
                {
                    ViewBag.SuccessMessage = "Record Saved Successfully.";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        public ActionResult CreateRoleMenu()
        {
            MenuRolesModel model = new MenuRolesModel();
            //ViewBag.menulist = MenuBLL.GetMenuList();
            ViewBag.menulist = new SelectList(MenuBLL.GetMenuList(), "Id", "MenuName");
            ViewBag.Rolelist = new SelectList(MenuModuleBLL.GetRoleList(),"Id","Name");
            
            //var data = MenuBLL.GetRoleByMenuId1(id);
            //model.AspNetRolesId = id;
            //model.CreatedbyUserId = data.CreatedbyUserId;
            //model.MenusId = data.MenusId;
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateRoleMenu(MenuRolesModel model)
        {
            if (ModelState.IsValid)
            {
                ViewBag.menulist = new SelectList(MenuBLL.GetMenuList(), "Id", "MenuName");
                ViewBag.Rolelist = new SelectList(MenuModuleBLL.GetRoleList(), "Id", "Name");
                bool create = MenuBLL.CreateMenuRole(model);
               
                if (!create)
                {
                    ViewBag.ErroMessage = "Something Went Wrong to save data";
                }
                else
                {
                    ViewBag.SuccessMessage = "Record Saved Successfully.";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        
        public ActionResult Create()
        {
            ViewBag.UsersList = new SelectList(MenuBLL.GetCompanyUserList(), "Id", "FullName");
            return View();
        }

        [HttpPost]
        public ActionResult Create(MenuModel model)
        {
            if (ModelState.IsValid)
            {
                model.MenuNumber = 0;
                   var userid = User.Identity.GetUserId();
                Guid Id = new Guid(userid);
                ViewBag.UsersList = new SelectList(MenuBLL.GetCompanyUserList(), "Id", "FullName");

                model.menulist = MenuBLL.GetMenuList();
                bool create = MenuBLL.CreateMenu(model, Id);
                if (!create)
                {
                    ViewBag.ErroMessage = "Something Went Wrong to save data";
                }
                else
                {
                    ViewBag.SuccessMessage = "Record Saved Successfully.";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        public ActionResult CreateModule(string id)
        {
            ModuleModel model = new ModuleModel();
            ViewBag.UsersList = new SelectList(MenuBLL.GetCompanyUserList(), "Id", "FullName");
           
            //model.CreatedByUserId = id;
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateModule(ModuleModel model)
        {
            if (ModelState.IsValid)
            {
                var userid = User.Identity.GetUserId();
                Guid Id = new Guid(userid);
                bool create = MenuBLL.CreateModule(model, Id);
                if (!create)
                {
                    ViewBag.ErroMessage = "Something Went Wrong to save data";
                }
                else
                {
                    ViewBag.SuccessMessage = "Record Saved Successfully.";
                    return RedirectToAction("Index");
                }
            }
            else
            {

            }
            return View(model);
        }
        public ActionResult CreateMenuModule()
        {
            MenuModuleModel model = new MenuModuleModel();
            ViewBag.menulist = new SelectList(MenuBLL.GetMenuList(), "Id", "MenuName");
            ViewBag.modulelist = new SelectList(MenuModuleBLL.GetModuleList(), "Id", "ModuleName");
            //ViewBag.UsersList = new SelectList(MenuBLL.GetCompanyUserList(), "Id", "FullName");                                
            return View(model);
        }

        [HttpPost]
        //public ActionResult CreateMenuModule(MenuModuleModel model,Guid ModuleId,Guid CreatedByUserId)
               public ActionResult CreateMenuModule(MenuModuleModel model)
        {
            if (ModelState.IsValid)
            {
                ViewBag.menulist = new SelectList(MenuBLL.GetMenuList(), "Id", "MenuName");
                model.CompanyModuleId = model.CompanyModuleId;                
                var userid = User.Identity.GetUserId();
                Guid Id = new Guid(userid);
                bool create = MenuModuleBLL.Createmodule(model,Id);
                if (!create)
                {
                    ViewBag.ErroMessage = "Something Went Wrong to save data";
                }
                else
                {
                    ViewBag.SuccessMessage = "Record Saved Successfully.";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        public ActionResult EditRole(Guid id,Guid UserId)
        {
            MenuRolesModel menu = new MenuRolesModel();
            ViewBag.RoleList = new SelectList(MenuBLL.GetRoleList(), "Id", "Name");
                var role = MenuBLL.GetRoleByMenu(id);
                var rolename = MenuBLL.GetAspRoleName(role);
                menu.AspNetRoleId =role;
                menu.RoleName = rolename;
                menu.CreatedByUserId = UserId;
                menu.MenuId = id;
                return View(menu);
            
        }
        [HttpPost]
        public ActionResult EditRole(MenuRolesModel model,Guid role)
        {
            if (ModelState.IsValid)
            {
                bool menu = MenuBLL.EditRole(model, role);
                if (!menu)
                {
                    ViewBag.ErroMessage = "Something Went Wrong";
                }
                else
                {
                    ViewBag.SuccessMessage = " Record Saved Successfully.";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        public ActionResult EditAspRole(string id)
        {
            var menu = MenuBLL.GetAspRoleId(id);

            return View(menu);

        }
        [HttpPost]
        public ActionResult EditAspRole(AspRoleModel model)
        {
            if (ModelState.IsValid)
            {
                bool menu = MenuBLL.EditAspRole(model);
                if (!menu)
                {
                    ViewBag.ErroMessage = "Something Went Wrong";
                }
                else
                {
                    ViewBag.SuccessMessage = " Record Saved Successfully.";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        

MGCERP/MGCERP/Areas/Admin/Controllers/MenuModuleController.cs
using MGCERP.BLL;
using MGCERP.Common.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MGCERP.Areas.Admin.Controllers
{
    public class MenuModuleController : Controller
    {
        // GET: Menu/MenuModule
        public ActionResult Index()
        {
            var modulelist = MenuModuleBLL.GetMenuModuleList();
            return Json(modulelist);
        }
        
         public ActionResult Menu(Guid id)
         {
            var modulelist = MenuModuleBLL.GetMenuName(id);
            return View(modulelist);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(AspRoleModel model)
        {
            if (ModelState.IsValid)
            {
                bool create = MenuModuleBLL.CreateRole(model);
                if (!create)
                {
                    ViewBag.ErroMessage = "Something Went Wrong to save data";
                }
                else
                {
                    ViewBag.SuccessMessage = "Record Saved Successfully.";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        public ActionResult CreateMenuModule(Guid id)
        {
            MenuModuleModel model = new MenuModuleModel();
            //ViewBag.menulist = MenuBLL.GetMenuList();
            ViewBag.menulist = new SelectList(MenuBLL.GetMenuList(), "Id", "Name");
            var data = MenuModuleBLL.GetCreatedUserId(id);
            model.CompanyModuleId = id;
            model.CreatedByUserId = data.CreatedByUserId;
            return View(model);
        }

        [HttpPost]
        //public ActionResult CreateMenuModule(MenuModuleModel model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        ViewBag.menulist = new SelectList(MenuBLL.GetMenuList(), "Id", "Name");
        //        bool create = MenuModuleBLL.Createmodule(model);
        //        if (!create)
        //        {
        //            ViewBag.ErroMessage = "Something Went Wrong to save data";
        //        }
        //        else
        //        {
        //            ViewBag.SuccessMessage = "Record Saved Successfully.";
        //            return RedirectToAction("Index");
        //        }
        //    }
        //    return View(model);
        //}
        
        public ActionResult ModuleIndex()
        {
            var modulelist = MenuModuleBLL.GetModuleList();
            return View(modulelist);
        }
        public ActionResult EditUserRole(string id)
        {

                var menu = MenuModuleBLL.GetRoleId(id);

                return View(menu);
        }
        [HttpPost]
        public ActionResult EditUserRole(AspRoleModel model)
        {
            if (ModelState.IsValid)
            {
                bool role = MenuModuleBLL.EditRole(model);
                if (!role)
                {
                    ViewBag.ErroMessage = "Something Went Wrong";
                }
                else
                {
                    ViewBag.SuccessMessage = " Record Saved Successfully.";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        public ActionResult EditMenu(Guid id)
        {
            //ViewBag.RoleList = new SelectList(MenuBLL.GetRoleList(), "Id", "Name");
            //if (id > 0)
            //{
                var menu = MenuModuleBLL.GetMenuId(id);

                return View(menu);
            //}

            //return View();
        }
        [HttpPost]
        public ActionResult EditMenu(MenuModuleModel model)
        {
            if (ModelState.IsValid)
            {
                bool menu = MenuModuleBLL.EditMenu(model);
                if (!menu)
                {
                    ViewBag.ErroMessage = "Something Went Wrong";
                }
                else
                {
                    ViewBag.SuccessMessage = " Record Saved Successfully.";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        public ActionResult DeleteMenuModule(Guid id)
        {
            if (ModelState.IsValid)
            {
                bool menu = MenuModuleBLL.DeleteModule(id);
                if (!menu)
                {
                    ViewBag.ErroMessage = "Something Went Wrong";
                }
                else
                {
                    ViewBag.SuccessMessage = " Record Saved Successfully.";
                    return RedirectToAction("Index");
                }
            }
            return View();
        }
        public ActionResult RoleIndex()
        {
            var Rolelist = MenuModuleBLL.GetRoleList();
            return View(Rolelist);
        }

    }
}

MGCERP/MGCERP/Areas/Admin/Views/MenuModule/CreateMenuModule.cshtml
@model MGCERP.Common.ViewModel.MenuModuleModel

@{
    ViewBag.Title = "CreateMenuModule";
    Layout = null;
}

<!DOCTYPE html>
<!--[if IE 9 ]><html class="ie ie9" lang="en" class="no-js"> <![endif]-->
<!--[if !(IE)]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<head>
    <title>Dynamic Table | KingAdmin - Admin Dashboard</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="KingAdmin - Bootstrap Admin Dashboard Theme">
    <meta name="author" content="The Develovers">
    <!-- CSS -->
    <link href="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/css/main.css" rel="stylesheet" />
    <link href="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/css/my-custom-styles.css" rel="stylesheet" />
    <!--[if lte IE 9]>
        <link href="assets/css/main-ie.css" rel="stylesheet" type="text/css"/>
        <link href="assets/css/main-ie-part2.css" rel="stylesheet" type="text/css"/>
    <![endif]-->
    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/kingadmin-dashboard-theme-v1.6.2/bonus/kingadmin-landing-page/assets/img/logo-MGCERP.jpg">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/Content/kingadmin-dashboard-theme-v1.6.2/bonus/kingadmin-landing-page/assets/img/logo-MGCERP.jpg">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Content/kingadmin-dashboard-theme-v1.6.2/bonus/kingadmin-landing-page/assets/img/logo-MGCERP.jpg">
    <link rel="apple-touch-icon-precomposed" sizes="57x57" href="~/Content/kingadmin-dashboard-theme-v1.6.2/bonus/kingadmin-landing-page/assets/img/logo-MGCERP.jpg">
    <link rel="shortcut icon" href="~/Content/kingadmin-dashboard-theme-v1.6.2/bonus/kingadmin-landing-page/assets/img/logo-MGCERP.jpg">
</head>
<body class="sidebar-fixed topnav-fixed ">
    <!-- WRAPPER -->
    <div id="wrapper" class="wrapper">
        <!-- TOP BAR -->
        <!-- END TOP BAR -->
        <!-- LEFT SIDEBAR -->
        <!-- END LEFT SIDEBAR -->
        <!-- MAIN CONTENT WRAPPER -->
        <div id="main-content-wrapper" class="content-wrapper ">
            <!-- top general alert -->
            <!-- end top general alert -->
            <!-- main -->
            <div class="content">
                <div class="main-header">
                </div>
                <div class="main-content">
                    <div class="widget widget-table">
                        <div class="widget-content">
                            @using (Html.BeginForm("CreateMenuModule","MenuModule",FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-horizontal">
                                
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(Model=>Model.ModuleId)
                                    @Html.HiddenFor(Model => Model.CreatedByUserId)
                                    @*<div class="form-group">
                                        @Html.LabelFor(model => model.ModuleId, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.ModuleId, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.ModuleId, "", new { @class = "text-danger" })
                                        </div>
                                    </div>*@

                                    @*<div class="form-group">
                                        @Html.LabelFor(model => model.MenuId, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.DropDownList("Menu", ViewBag.menulist as SelectList, "-select-", new { id = "", Text = "Menu", value = "Menu", @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.MenuId, "", new { @class = "text-danger" })
                                        </div>
                                    </div>*@
                                    <div class="form-group">
                                        <div class="control-label col-md-2">
                                            MenuId
                                        </div>
                                        <div class="col-md-10">
                                            
                                            @Html.DropDownList("MenuId", ViewBag.menulist as SelectList, "-select-", new { id = "", Text = "MenuId", value = "MenuId", @class = "form-control" })
                                            @*@Html.DropDownList("name", ViewBag.RoleList as SelectList, "Id", "Name");*@
                                            @*@Html.DropDownListFor("Role",new SelectList(ViewBag.RoleList, "Id", "Name"), "- Please Select Role-", new { @class = "form-control" })*@
                                        </div>
                                    </div>

                                    @*<div class="form-group">
                                        @Html.LabelFor(model => model.CreatedByUserId, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.CreatedByUserId, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.CreatedByUserId, "", new { @class = "text-danger" })
                                        </div>
                                    </div>*@

                                    @*<div class="form-group">
                                        @Html.LabelFor(model => model.CreatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.CreatedOn, "", new { @class = "text-danger" })
                                        </div>
                                    </div>*@

                                    @*<div class="form-group">
                                        @Html.LabelFor(model => model.UpdatedByUserId, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.UpdatedByUserId, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.UpdatedByUserId, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.UpdatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.UpdatedOn, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.UpdatedOn, "", new { @class = "text-danger" })
                                        </div>
                                    </div>*@

                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="Create" class="btn btn-default" />
                                        </div>
                                    </div>
                                </div>
                            }

                            <div>
                                @Html.ActionLink("Back to List", "Index")
                            </div>
                        </div>
                    </div>
                </div>



            </div>
        </div>
    </div>
    <!-- END CONTENT WRAPPER -->
    <!-- END WRAPPER -->
    <!-- Javascript -->
    <script src="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/js/jquery/jquery-2.1.0.min.js"></script>
    <script src="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/js/bootstrap/bootstrap.js"></script>
    <script src="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/js/plugins/modernizr/modernizr.js"></script>
    <script src="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/js/plugins/bootstrap-tour/bootstrap-tour.custom.js"></script>
    <script src="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/js/plugins/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/js/king-common.js"></script>
    <script src="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/js/plugins/datatable/jquery.dataTables.min.js"></script>
    <script src="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/js/plugins/datatable/exts/dataTables.colVis.bootstrap.js"></script>
    <script src="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/js/plugins/datatable/exts/dataTables.colReorder.min.js"></script>
    <script src="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/js/plugins/datatable/exts/dataTables.tableTools.min.js"></script>
    <script src="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/js/plugins/datatable/dataTables.bootstrap.js"></script>
    <script src="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/js/plugins/jqgrid/jquery.jqGrid.min.js"></script>
    <script src="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/js/plugins/jqgrid/i18n/grid.locale-en.js"></script>
    <script src="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/js/plugins/jqgrid/jquery.jqGrid.fluid.js"></script>
    <script src="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/js/plugins/bootstrap-datepicker/bootstrap-datepicker.js"></script>
    <script src="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/js/king-table.js"></script>
    <script src="~/Content/kingadmin-dashboard-theme-v1.6.2/theme/assets/js/king-components.js"></script>
</body>
</html>